= Filosofía del sistema posicional
José Pepé <jose.s.contacto@gmail.com>
:toc:

Este documento provee una descripción de la filosofía del sistema posicional.

== Acercamiento al desarrollo de la filosofía

- El acercamiento se da mediante métodos Holísticos

== Objetivos del desarrollo 

El objetivo principal es desarrollar la "discusión fundamental" de la comprensión de los sistemas y problemáticas donde el sistema posicional debe desplegar sus soluciones.
Hay que definir a qué problemas debe orientarse el sistema posicional, así cómo las asunciones y creencias cuidadosamente discutidas, elegidas y sembradas para obtener un fruto funcional y rigurosamente basado.

El objetivo secundario es el desarrollo, basado en esa discusión fundamental, de un approach general perteneciente al sistema posicional, que permita entonces el desarrollo de diferentes metodologías para los principales y generales problemas a resolver.
La elección de prácticas se basa en criterios a formular en esta filosofía.

Otro objetivo secundario es la formulación de un lenguaje obicuo propio, que el sistema posicional heredará, el cual se verá a lo largo de toda la propuesta tanto en las áreas más abstractas, como en varias concretitudes.

== Objetivos del sistema posicional

El objetivo principal es mejorar la situación vital del individuo, acercándolo a su concepto racional de felicidad.

Los objetivos secundarios y heredados son:

. Aumentar la comprensión del individuo sobre sus objetivos y concepto de felicidad
. Manejar la complejidad de información en la vida
. Aumentar la inteligencia estratégica individual 
. Aumentar la productividad
. Aprovechar lo mejor posible los recursos.

Los principios son:

A más importante/prioritario un asunto, más complejidad se le da a su administracion (sea organizacion, planificación, ejecución, inversion, etc) y a menos importante, menos complejo.

El individuo, por uso demostrable de razón, puede decidir ignorar el sistema de alguna manera eventualmente, o crear métodos propios y otras extensiones mientras se mantenga congruente con la filosofía.

== Modelos de datos del sistema (o elementos)

Individuo: Agente causal principal del sistema. 
Contiene: 

. Identidad para el área sociológica 
. Área sociológica 
. Área de su saber 
. Área de producción 
. Área de sus recursos

Input: Información nueva que aparece en el consciente
Contiene: 

. Información nueva 
. relaciónes con los objetivos de medio plazo 
. prioridad (relativa y dependiente del anterior) 
. Significado (relativo al individuo) e Impacto (Qué debería hacer el individuo frente al significado)

Inbox: Contenedor físico o digital de inputs
Contiene:

. Espacio
. Separadores
. Filtros

Método: Definicion concreta de un flujo de trabajo para un asunto metodologizable

Situación actual:

== El individuo

El sistema posicional tiene cómo problema principal el llevar a un individuo humano a la mejor posicion en la vida posible, entendiendo "mejor" cómo el conjunto de creencias, visiones y estados futuros en el cual el individuo cree que está su objetivo vital.

El individuo se llama de esa forma, y no "Persona", porque el primer término está más cerca del concepto "especie humana" que se relaciona más al objetivo principal que el concepto "Persona" el cual no se diferencia de conceptos de Derecho o Ética, dos áreas que no son de interés principal del sistema.

Para mayor simplicidad de lectura, es recomendable entender como Individuo a usted mismo/a. Sin embargo, por motivos de explicación, la redacción siempre mantendrá el término inalterable.

== Áreas del individuo

El individuo consiste en un conjunto de áreas principales:

. Interpersonal: El individuo se relaciona voluntaria y/o forzosamente con otros, y también con conjuntos de ellos, para conseguir sus objetivos y ayudar a conseguir los objetivos de sus individuos cercanos.

. Cognitiva: El individuo sabe cosas en diferentes niveles. Pero la definición no queda simplemente en un almacen de conocimientos, si no que se expande al concepto de epistemología, donde el individuo se preocupa por validar y justificar racionalmente sus conocimientos, sus fuentes de aprendizaje, por reconocer sus propias creencias base, por reconocer y optimizar su forma de estudio, y demás. No existe el concepto de particularismo epistemológico, es decir, el saber sin interesarse del por qué y cómo se sabe.

. Productiva: El individuo es un agente activo en el mundo fáctico, y desarrolla proyectos que corresponden a todo un árbol de objetivos individuales que debe tenerse en cuenta al momento de invertir y priorizar.

. De recusos: El individuo tiene poder solo si tiene recursos de algun tipo. Pueden ser recursos dentro del área sociológica, cómo la persuación o el dinero, pueden ser recursos del saber, como el conocimiento o experiencia, pueden ser recursos de la producción, como herramientas y sistemas propios, y demás áreas.

== Lenguaje específico

=== Para la acción 

. Asunto: Es una necesidad concreta de acción que tiene el individuo. Se identifican 3 tipos de asunto, Proyectos, Tareas y Acciones. Por accidente Y NUNCA POR DEFINICIÓN un proyecto es más complejo que una tarea, y a su vez, ésta es más compleja que una acción. Responde a la situación actual del individuo. Componer a los proyectos por solo tareas, y a estas por solo acciones, sería un error dado que se deja de lado la información y los recursos necesarios para completarlos a cada uno. Además, genera en la ambiguedad de la definición típica, una falsa concepción que parte de entender que "el trabajo solo es actuar, y no su definición y los recursos que requiere"

. Acción: Es la mínima unidad absoulta de acción medible del individuo. Es además algo concreto, es nacida del análisis de la situación actual del individuo (Recursos como el conocimiento, compromisos, etc) con objetivo de acercarse a completar el asunto. Depende del conocimiento actual casi totalmente, dado que adquirir más conocimientos es una acción por si mismas.

. Tarea: Es una propuesta de lo que se debe hacer para completar un asunto. Las tareas sirven principalmente para socializar las acciones o trabajo, y el conocimiento mediante la comunicación en términos generales. También le sirven al individuo para planificar proyectos.

. Proyecto: Es la planificación de la utilización de recursos del individuo, organizada para la consecución de un objetivo principal que le da sentido, y opcionalmente objetivos secundarios, que busca conseguir uno o más beneficios alineados con los objetivos de identidad del individuo. Responde entonces a la situación actual del individuo y a la identidad deseada de éste.

. Estado de los asuntos: Es una forma de determinar la evolución de los asuntos; puede estar pendiente si aún no se está accionando, puede estar completado si ya fue accionado, puede estar pendiente porque está bloqueado con otro asunto que impide el accionar, puede estar cancelado porque se decidió suspender el accionar.
